"""
Django settings for coursework_platform project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c-4518fi$r49-yp451twoj*oj^hro%+7!-5#lxm-dk3jpf&t7q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ваши приложения (в правильном порядке зависимостей)
    'users.apps.UsersConfig',  # 1. Базовое приложение пользователей
    'payments.apps.PaymentsConfig',  # 2. Приложение для платежей (зависит от users)
    'orders.apps.OrdersConfig',  # 3. Приложение заказов (зависит от users и payments)
    'disputes.apps.DisputesConfig',  # 4. Приложение споров (зависит от orders)
    'messaging.apps.MessagingConfig',  # 5. Приложение сообщений

    # Рекомендуемые сторонние пакеты


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AuthRequiredMiddleware',
]

ROOT_URLCONF = 'coursework_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'orders.context_processors.dispute_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'coursework_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'users.User'

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CELERY_BEAT_SCHEDULE = {
    'check-auto-completion': {
        'task': 'orders.tasks.check_auto_completion',
        'schedule': 3600.0,  # Каждый час
    },
}


# Разрешенные URL без авторизации
AUTH_EXEMPT_URLS = [
    '/about/',  # Страница "О нас"
    '/contact/',  # Страница контактов
    '/terms/',   # Условия использования
]


LOGIN_URL = 'login'  # Имя URL вашей страницы входа
LOGIN_REDIRECT_URL = 'profile'  # Куда перенаправлять после входа



# Для разработки - уменьшенный срок спора (1 минута)
DISPUTE_EXPIRE_DAYS = 7 if not DEBUG else 1/1440  # 1 минута в режиме отладки



# Stripe Settings
STRIPE_SECRET_KEY = 'sk_test_51PbIvlCDmlPA0aUAePWvtfNejRVY6xPK3U00HUwGrD8cr18lIuuiAZkk18FRnheYCdhs6mUeFNyoHBlnVIwMa02f00kTOLwtYU'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51PbIvlCDmlPA0aUAkJY2eHmaNwirEKJw7PoYtEY01udCUGrgsbVfhhxypozDOoJ2lmthzXBNLZgPnVmB1UCAfa6500oKOdpA6I'
STRIPE_CURRENCY = 'rub'  # Валюта платежей
STRIPE_WEBHOOK_SECRET = ''  # Для вебхуков (если используете)

# Доменные настройки
DOMAIN = 'http://localhost:8000'  # Для тестирования
# DOMAIN = 'https://ваш-сайт.com'  # Для продакшена






