# Generated by Django 5.1.5 on 2025-06-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_options_remove_transaction_comment_and_more'),
        ('users', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
