# Generated by Django 5.1.5 on 2025-06-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_transaction_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
