# Generated by Django 4.2.1 on 2025-04-23 19:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frozen_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
