# Generated by Django 5.1.5 on 2025-06-07 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_frozen_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_request_payout', 'Can request payout')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
