# Generated by Django 4.2.1 on 2025-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='admin_decision',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='employee_comment',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='resolved_by',
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_for',
            field=models.CharField(blank=True, choices=[('customer', 'Заказчик'), ('employee', 'Исполнитель')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает решения'), ('resolved', 'Решен')], default='pending', max_length=20),
        ),
    ]
