# Generated by Django 4.2.1 on 2025-04-30 19:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_dispute_admin_remove_dispute_admin_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='resolution',
            field=models.CharField(blank=True, choices=[('client', 'Клиенту'), ('executor', 'Исполнителю')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
