# Generated by Django 4.2.1 on 2025-05-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dispute_resolution_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='resolution',
        ),
    ]
