# Generated by Django 4.2.1 on 2025-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_dispute_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='resolved_for',
            field=models.CharField(blank=True, choices=[('customer', 'Клиент'), ('executor', 'Исполнитель')], max_length=10, null=True),
        ),
    ]
