# Generated by Django 4.2.1 on 2025-05-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_dispute_resolved_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает исполнителя'), ('price_proposed', 'Ожидает подтверждения цены'), ('waiting_approval', 'Ожидает подтверждения'), ('in_progress', 'В работе'), ('submitted', 'Отправлено клиенту'), ('approved', 'Принято клиентом'), ('rejected', 'Отклонено клиентом'), ('completed', 'Завершено'), ('auto_completed', 'Автоматически завершено'), ('refunded', 'Возврат средств'), ('closed', 'Закрыт')], default='pending', max_length=25, verbose_name='Статус'),
        ),
    ]
