# Generated by Django 5.1.5 on 2025-06-07 20:32

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_dispute_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputemessage',
            name='dispute',
        ),
        migrations.RemoveField(
            model_name='disputemessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='order',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='payoutrequest',
            name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='priceproposal',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='priceproposal',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='priceproposal',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dispute_deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_price_approved',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payout_due_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='proposed_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rejection_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=orders.models.rename_uploaded_file),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает исполнителя'), ('price_proposed', 'Ожидает подтверждения цены'), ('waiting_approval', 'Ожидает подтверждения'), ('in_progress', 'В работе'), ('submitted', 'Отправлено клиенту'), ('approved', 'Принято клиентом'), ('rejected', 'Отклонено клиентом'), ('completed', 'Завершено'), ('auto_completed', 'Автоматически завершено'), ('refunded', 'Возврат средств'), ('closed', 'Закрыт')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='tag',
            field=models.CharField(blank=True, choices=[('ready_work', 'Готовая работа'), ('consultation', 'Консультация'), ('final_touches', 'Финальные штрихи')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_type',
            field=models.CharField(choices=[('coursework', 'Курсовая работа'), ('diploma', 'Дипломная работа'), ('essay', 'Эссе'), ('research', 'Реферат'), ('lab_work', 'Лабораторная'), ('other', 'Другое')], default='coursework', max_length=20),
        ),
        migrations.DeleteModel(
            name='Dispute',
        ),
        migrations.DeleteModel(
            name='DisputeMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='PayoutRequest',
        ),
        migrations.DeleteModel(
            name='PriceProposal',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
