# Generated by Django 5.1.5 on 2025-06-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
