# Generated by Django 5.1.5 on 2025-06-08 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_client_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_comment',
        ),
    ]
